"""empty message

Revision ID: bc15a97640dd
Revises: 7802008b8b44
Create Date: 2018-11-22 20:47:00.808905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc15a97640dd'
down_revision = '7802008b8b44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'icon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('icon', mysql.VARCHAR(length=40), nullable=True))
    # ### end Alembic commands ###
